In [1]:
import pandas as pd
wdi_imp = pd.read_pickle('wdi_imp.pkl')

In [2]:
wdi_imp.describe()

,access_to_electricity_pct,atms_per_100000,compulsory_education_years,health_expenditure_pct_of_gdp,gdp_per_capita_usd,gdp_per_capita_ppp,life_expectancy_female,life_expectancy_male,life_expectancy,population_density,population,alcohol_consumption_per_capita,unemployment_rate_female,unemployment_rate_male,unemployment_rate,year,is_region
count,434.000000,434.000000,434.000000,434.000000,434.000000,434.000000,434.000000,434.000000,434.000000,434.000000,4.340000e+02,434.000000,434.000000,434.000000,434.000000,434.000000,434.000000
mean,84.215517,46.784191,9.668580,6.446628,13599.891623,19925.226075,74.569474,69.866522,72.176272,209.423845,3.690135e+08,5.953448,8.404762,6.465617,7.047682,2017.500000,0.211982
std,24.389620,42.629723,2.169753,2.603615,18647.562977,19970.698889,7.676443,7.144252,7.334379,745.602623,1.049035e+09,3.234751,6.863858,4.535745,5.026820,0.500577,0.409184
min,9.300000,1.213235,5.000000,2.138482,271.752044,773.571858,54.354000,49.837000,52.240000,2.004286,1.019980e+05,0.003000,0.369000,0.052000,0.110000,2017.000000,0.000000
25%,70.842500,12.020894,9.000000,4.516610,1971.836316,4989.813770,69.050750,65.297750,66.988750,35.162379,4.312760e+06,3.762983,3.893250,3.796250,3.946283,2017.000000,0.000000
50%,98.912941,38.034455,10.000000,6.097962,5783.711368,13108.453526,76.088500,70.813500,73.585501,69.967215,1.604842e+07,5.684597,5.836087,5.351708,5.606500,2017.500000,0.000000
75%,100.000000,64.213716,11.000000,7.937957,15561.550814,28646.342748,80.144500,74.659500,77.162500,133.532197,1.026882e+08,8.269917,10.286000,8.001815,9.051000,2018.000000,0.000000
max,100.000000,272.592801,16.000000,17.003614,116654.261067,116786.479974,87.700000,82.300000,84.934146,7952.998418,7.591945e+09,15.090000,42.769001,25.238001,27.070999,2018.000000,1.000000